//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("src.Localization.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập vào ứng dụng.  Vui lòng liên hệ với người quản trị..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn không tồn tại trên hệ thống. Vui lòng liên hệ phòng tuyển sinh tại VAS để cập nhật thông tin này. Xin cảm ơn !!!.
        /// </summary>
        public static string AccountNotExisting {
            get {
                return ResourceManager.GetString("AccountNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh có tiền sử bệnh tật/dị ứng nào mà có thể nguy hiểm tới sức khỏe* không?&lt;br&gt;
        ///(Ví dụ: dị ứng nghiêm trọng với thuốc, nọc của ong hoặc thức ăn, động kinh, tiểu đường, bệnh tim).
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã hoàn tất thiết lập mật khẩu. Vui lòng thử đăng nhập lại !.
        /// </summary>
        public static string AlreadySetPassword {
            get {
                return ResourceManager.GetString("AlreadySetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string authorization_status {
            get {
                return ResourceManager.GetString("authorization_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay trở lại.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string btn_accept {
            get {
                return ResourceManager.GetString("btn_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        public static string btn_continue {
            get {
                return ResourceManager.GetString("btn_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại mã xác thực.
        /// </summary>
        public static string btn_resend_verification_code {
            get {
                return ResourceManager.GetString("btn_resend_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt sử dụng.
        /// </summary>
        public static string button_set_active {
            get {
                return ResourceManager.GetString("button_set_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngưng sử dụng.
        /// </summary>
        public static string button_set_inactive {
            get {
                return ResourceManager.GetString("button_set_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click vào đây để tiếp tục thực hiện đăng ký khác.
        /// </summary>
        public static string click_to_continue_making_other_authorizations {
            get {
                return ResourceManager.GetString("click_to_continue_making_other_authorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu và mật khẩu xác nhận không khớp..
        /// </summary>
        public static string ConfirmPassword_Message {
            get {
                return ResourceManager.GetString("ConfirmPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *  Vui nhập thiết lập mật khẩu.
        /// </summary>
        public static string CreatePassWord_Message {
            get {
                return ResourceManager.GetString("CreatePassWord_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng không nhập ngày nhỏ hơn hiện tại.
        /// </summary>
        public static string DateEarlierCurrentDate {
            get {
                return ResourceManager.GetString("DateEarlierCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng không nhập ngày nhỏ hơn đến ngày .
        /// </summary>
        public static string DateEarlierEndDate {
            get {
                return ResourceManager.GetString("DateEarlierEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tháng năm sinh của {0} không đúng !.
        /// </summary>
        public static string DateOfBirthInputNotCorrect {
            get {
                return ResourceManager.GetString("DateOfBirthInputNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBirthStudent {
            get {
                return ResourceManager.GetString("DateOfBirthStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ngày tháng năm sinh của học sinh vừa chọn theo định ngày/tháng/năm.
        /// </summary>
        public static string DateOfBirthStudent_Message {
            get {
                return ResourceManager.GetString("DateOfBirthStudent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn cập nhật cho tất cả học sinh ?.
        /// </summary>
        public static string dlg_update_for_all_students {
            get {
                return ResourceManager.GetString("dlg_update_for_all_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên lớp.
        /// </summary>
        public static string EnterClassName {
            get {
                return ResourceManager.GetString("EnterClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập xác nhận mật khẩu.
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập không ăn từ ngày.
        /// </summary>
        public static string EnterFromDate {
            get {
                return ResourceManager.GetString("EnterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lý do.
        /// </summary>
        public static string EnterReason {
            get {
                return ResourceManager.GetString("EnterReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã học sinh.
        /// </summary>
        public static string EnterStudentCode {
            get {
                return ResourceManager.GetString("EnterStudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên học sinh.
        /// </summary>
        public static string EnterStudentName {
            get {
                return ResourceManager.GetString("EnterStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đến ngày.
        /// </summary>
        public static string EnterToDate {
            get {
                return ResourceManager.GetString("EnterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số ngày không ăn.
        /// </summary>
        public static string EnterTotalNumberOfDays {
            get {
                return ResourceManager.GetString("EnterTotalNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tài khoản.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin người uỷ thác bằng địa chỉ email.
        /// </summary>
        public static string error_msg_can_not_find_madator_by_email_address {
            get {
                return ResourceManager.GetString("error_msg_can_not_find_madator_by_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin đăng ký buổi ăn.
        /// </summary>
        public static string error_msg_can_not_find_meal_information {
            get {
                return ResourceManager.GetString("error_msg_can_not_find_meal_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin uỷ quyền.
        /// </summary>
        public static string error_msg_can_not_find_power_of_attorney_information {
            get {
                return ResourceManager.GetString("error_msg_can_not_find_power_of_attorney_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật do bạn không phải là người chủ sở hữu thông tin này.
        /// </summary>
        public static string error_msg_can_not_update_because_you_are_not_owner {
            get {
                return ResourceManager.GetString("error_msg_can_not_update_because_you_are_not_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng không nhập quá 100 kí tự.
        /// </summary>
        public static string Exceed100Characters {
            get {
                return ResourceManager.GetString("Exceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng không nhập quá 50 kí tự.
        /// </summary>
        public static string Exceed50Characters {
            get {
                return ResourceManager.GetString("Exceed50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không ăn từ ngày.
        /// </summary>
        public static string from_day_no_meal {
            get {
                return ResourceManager.GetString("from_day_no_meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        public static string label_active {
            get {
                return ResourceManager.GetString("label_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string label_address {
            get {
                return ResourceManager.GetString("label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng giấy này tôi đồng ý đăng ký cho em.
        /// </summary>
        public static string label_agree_to_authorized {
            get {
                return ResourceManager.GetString("label_agree_to_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string label_agreed {
            get {
                return ResourceManager.GetString("label_agreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string label_alert {
            get {
                return ResourceManager.GetString("label_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ CHO HỌC SINH.
        /// </summary>
        public static string label_authorized_person {
            get {
                return ResourceManager.GetString("label_authorized_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ BUỔI ĂN.
        /// </summary>
        public static string label_brand {
            get {
                return ResourceManager.GetString("label_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở.
        /// </summary>
        public static string label_campus {
            get {
                return ResourceManager.GetString("label_campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        public static string label_class {
            get {
                return ResourceManager.GetString("label_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận Sổ tay Phụ huynh - Học sinh và Quy định Nhà trường của Quý phụ huynh có hiệu lực từ ngày.
        /// </summary>
        public static string label_confirmation_effective {
            get {
                return ResourceManager.GetString("label_confirmation_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng xác nhận.
        /// </summary>
        public static string label_confirmation_status {
            get {
                return ResourceManager.GetString("label_confirmation_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dùng cho các học sinh bên dưới.
        /// </summary>
        public static string label_copy_for_all_students {
            get {
                return ResourceManager.GetString("label_copy_for_all_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string label_date_created {
            get {
                return ResourceManager.GetString("label_date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string label_date_of_birth {
            get {
                return ResourceManager.GetString("label_date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string label_details {
            get {
                return ResourceManager.GetString("label_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực.
        /// </summary>
        public static string label_effective_date {
            get {
                return ResourceManager.GetString("label_effective_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string label_email_address {
            get {
                return ResourceManager.GetString("label_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp Quý phụ huynh không nhớ số điện thoại hoặc địa chỉ email đã đăng ký với Nhà trường, vui lòng liên hệ với bộ phận tuyển sinh tại cơ sở theo số hotline bên dưới để được hỗ trợ..
        /// </summary>
        public static string label_forgot_registered_information {
            get {
                return ResourceManager.GetString("label_forgot_registered_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối.
        /// </summary>
        public static string label_grade {
            get {
                return ResourceManager.GetString("label_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCCD/Hộ chiếu số.
        /// </summary>
        public static string label_id_passport {
            get {
                return ResourceManager.GetString("label_id_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        public static string label_id_passport_issue_by {
            get {
                return ResourceManager.GetString("label_id_passport_issue_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp ngày.
        /// </summary>
        public static string label_id_passport_issued_date {
            get {
                return ResourceManager.GetString("label_id_passport_issued_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không sử dụng.
        /// </summary>
        public static string label_inactive {
            get {
                return ResourceManager.GetString("label_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thông tin.
        /// </summary>
        public static string label_information_verification {
            get {
                return ResourceManager.GetString("label_information_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật cuối cùng.
        /// </summary>
        public static string label_last_updated {
            get {
                return ResourceManager.GetString("label_last_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà trường đã gửi cho bạn một {0} có mã số xác thực. Để hoàn tất xác minh, Quý phụ huynh vui lòng nhập mã xác thực gồm 6 chữ số..
        /// </summary>
        public static string label_message_sent_verification_code {
            get {
                return ResourceManager.GetString("label_message_sent_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác nhận.
        /// </summary>
        public static string label_not_yet_confirmed {
            get {
                return ResourceManager.GetString("label_not_yet_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to được phép không tham gia ăn tại trường.
        /// </summary>
        public static string label_onbehalf {
            get {
                return ResourceManager.GetString("label_onbehalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHỤ HUYNH/NGƯỜI GIÁM HỘ.
        /// </summary>
        public static string label_parent_legal_guardian {
            get {
                return ResourceManager.GetString("label_parent_legal_guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string label_parents_name {
            get {
                return ResourceManager.GetString("label_parents_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string label_phone_number {
            get {
                return ResourceManager.GetString("label_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý phụ huynh vui lòng chọn từng học sinh hoặc nhiều học sinh trong danh sách bên dưới để thực hiện xác đơn đăng ký..
        /// </summary>
        public static string label_please_select_student_for_confirmation {
            get {
                return ResourceManager.GetString("label_please_select_student_for_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ huynh cam kết chịu trách nhiệm hoàn toàn về vấn đề vệ sinh an toàn thực phẩm cho phần ăn gia đình chuẩn bị cho học sinh..
        /// </summary>
        public static string label_powrer_of_attorney_terms_and_condition_1 {
            get {
                return ResourceManager.GetString("label_powrer_of_attorney_terms_and_condition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để đảm bảo lịch sinh hoạt chung của học sinh với lớp, Phụ huynh cam kết phần ăn gia đình chuẩn bị cho học sinh luôn sẵn sàng trước giờ ăn của học sinh.
        /// </summary>
        public static string label_powrer_of_attorney_terms_and_condition_2 {
            get {
                return ResourceManager.GetString("label_powrer_of_attorney_terms_and_condition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy ủy quyền này có hiệu lực kể từ ngày ký cho đến khi tôi có thông báo khác..
        /// </summary>
        public static string label_powrer_of_attorney_terms_and_condition_3 {
            get {
                return ResourceManager.GetString("label_powrer_of_attorney_terms_and_condition_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mối quan hệ với tôi.
        /// </summary>
        public static string label_relationship {
            get {
                return ResourceManager.GetString("label_relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại hoặc email để đăng nhập vào hệ thống xác nhận..
        /// </summary>
        public static string label_required_input_for_login {
            get {
                return ResourceManager.GetString("label_required_input_for_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại OTP trong.
        /// </summary>
        public static string label_resend_OPT_in {
            get {
                return ResourceManager.GetString("label_resend_OPT_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy định Nhà trường.
        /// </summary>
        public static string label_school_rules {
            get {
                return ResourceManager.GetString("label_school_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string label_select {
            get {
                return ResourceManager.GetString("label_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã học sinh.
        /// </summary>
        public static string label_student_code {
            get {
                return ResourceManager.GetString("label_student_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên học sinh.
        /// </summary>
        public static string label_student_name {
            get {
                return ResourceManager.GetString("label_student_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string label_textbox_email_phone_login {
            get {
                return ResourceManager.GetString("label_textbox_email_phone_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHÀO MỪNG QUÝ PHỤ HUYNH ĐẾN VỚI HỆ THỐNG ĐĂNG KÝ BUỔI ĂN.
        /// </summary>
        public static string label_welcome_message {
            get {
                return ResourceManager.GetString("label_welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ BUỔI ĂN.
        /// </summary>
        public static string lable_handbook_schoolrules_online_confirmation {
            get {
                return ResourceManager.GetString("lable_handbook_schoolrules_online_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập để sử dụng hệ thống.
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string Logout_button {
            get {
                return ResourceManager.GetString("Logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ ĐĂNG KÝ BUỔI ĂN.
        /// </summary>
        public static string meal_history {
            get {
                return ResourceManager.GetString("meal_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức không ăn.
        /// </summary>
        public static string meal_registration {
            get {
                return ResourceManager.GetString("meal_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Trong trường hợp học sinh có bệnh tật có thể gây nguy hiểm đến sức khỏe, GIA ĐÌNH có trách nhiệm thông báo cho Nhà trường và nhân viên y tế của Nhà trường biết trước khi con/em mình tham gia Chương trình Trại hè.&lt;br&gt;
        ///Học sinh có đang dùng thuốc hoặc đang điều trị mà có thể ảnh hưởng đến việc tham gia các hoạt động của Chương trình Trại hè không? (Ví dụ: đang dùng thuốc hen suyễn).
        /// </summary>
        public static string Medical_History {
            get {
                return ResourceManager.GetString("Medical_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý Phụ huynh đã hoàn tất xác nhận. Xin cám ơn!.
        /// </summary>
        public static string message_completed_confirmation {
            get {
                return ResourceManager.GetString("message_completed_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại trong hệ thống. Quý phụ huynh vui lòng thử lại !.
        /// </summary>
        public static string message_email_not_exist {
            get {
                return ResourceManager.GetString("message_email_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc số điện thoại không tồn tại trong hệ thống. Quý phụ huynh vui lòng thử lại !.
        /// </summary>
        public static string message_email_phone_number_not_exist {
            get {
                return ResourceManager.GetString("message_email_phone_number_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý phụ huynh vui lòng nhập mã xác thực để tiếp tục !.
        /// </summary>
        public static string message_entere_validation_code {
            get {
                return ResourceManager.GetString("message_entere_validation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của quý phụ huynh đã tạm khoá vì lý do yêu cầu gửi mã xác thực nhiều lần. Vui lòng liên hệ đến số hotline bên dưới website để được hỗ trợ !.
        /// </summary>
        public static string message_input_wrong_code_many_time {
            get {
                return ResourceManager.GetString("message_input_wrong_code_many_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực bạn đã nhập không hợp lệ. Vui lòng thử lại!.
        /// </summary>
        public static string message_invalid_code {
            get {
                return ResourceManager.GetString("message_invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một email có mã xác minh vừa được gửi cho bạn. Vui lòng nhập mã xác thực mới.
        /// </summary>
        public static string message_sent_new_validation_code {
            get {
                return ResourceManager.GetString("message_sent_new_validation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình xử lý. Quý phụ huynh vui lòng thử lại. Xin cảm ơn !.
        /// </summary>
        public static string message_something_went_wrong {
            get {
                return ResourceManager.GetString("message_something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập quá hạn, Vui lòng đăng nhập lại !.
        /// </summary>
        public static string message_user_expired {
            get {
                return ResourceManager.GetString("message_user_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không hoạt động quá lâu. Chỉ còn 2 phút trước khi trở về trang chủ!.
        /// </summary>
        public static string message_user_inactivity {
            get {
                return ResourceManager.GetString("message_user_inactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu của học sinh vừa nhập !.
        /// </summary>
        public static string NotFoundStudent {
            get {
                return ResourceManager.GetString("NotFoundStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa không?.
        /// </summary>
        public static string notification_delete {
            get {
                return ResourceManager.GetString("notification_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày không ăn.
        /// </summary>
        public static string number_day_no_meal {
            get {
                return ResourceManager.GetString("number_day_no_meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọn ngày.
        /// </summary>
        public static string option_meal_registration_1 {
            get {
                return ResourceManager.GetString("option_meal_registration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáng.
        /// </summary>
        public static string option_meal_registration_2 {
            get {
                return ResourceManager.GetString("option_meal_registration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tối thiểu phải {0} ký tự trở lên và không dài quá {1} ký tự..
        /// </summary>
        public static string Password_atleast {
            get {
                return ResourceManager.GetString("Password_atleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn học sinh để xác thực tài khoản.
        /// </summary>
        public static string PleaseSelectStudent {
            get {
                return ResourceManager.GetString("PleaseSelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ cho phép nhập ký tự và chữ số..
        /// </summary>
        public static string RegularExpression_Username {
            get {
                return ResourceManager.GetString("RegularExpression_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        public static string Reset_button {
            get {
                return ResourceManager.GetString("Reset_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn năm học.
        /// </summary>
        public static string SelectSchoolYear {
            get {
                return ResourceManager.GetString("SelectSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string SignIn_button {
            get {
                return ResourceManager.GetString("SignIn_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công !!!.
        /// </summary>
        public static string success_msg_update_success {
            get {
                return ResourceManager.GetString("success_msg_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách học sinh đăng ký buổi ăn tại VAS.
        /// </summary>
        public static string title_report {
            get {
                return ResourceManager.GetString("title_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string to_day_no_meal {
            get {
                return ResourceManager.GetString("to_day_no_meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường Quốc tế Việt Úc (&lt;strong&gt;VAS&lt;/strong&gt;).
        /// </summary>
        public static string VAS {
            get {
                return ResourceManager.GetString("VAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
